=pod

=head1 NAME

Perl::Critic::Policy::Variables::NameReuse - Don't reuse names for different
types of variables

=head1 SYNOPSIS

  perlcritic --single-policy=Variables::NameReuse script.pl
  perlcritic --single-policy=Variables::NameReuse lib/

  # .perlcriticrc
  severity = 1
  only = 1
  [Variables::NameReuse]

=head1 DESCRIPTION

This policy checks for the existence of multiple variables with the same name
in a file. This can be confusing especially when accessing elements of
variables or using L<list or key-value slices|perldata/Slices>. For example,
the code could access both C<$foo> and C<$foo[0]> but these actually refer to
the unrelated variables C<$foo> and C<@foo>.

  my $foo = @foo;             # not ok
  my @bar = @bar{'a','b'};    # not ok
  my $count = @foo;           # ok
  my @values = @bar{'a','b'}; # ok

=head1 AFFILIATION

This policy has no affiliation.

=head1 CONFIGURATION

This policy is not configurable except for the standard options.  

=head1 BUGS

Report any issues on the public bugtracker.

=head1 AUTHOR

Dan Book <dbook@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is Copyright (c) 2018 by Dan Book.

This is free software, licensed under:

  The Artistic License 2.0 (GPL Compatible)

=head1 SEE ALSO

L<Perl::Critic::Policy::Variables::ProhibitReusedNames> - instead prohibits
redeclaring the same variable name across different scopes

=cut
